AWSTemplateFormatVersion: 2010-09-09

Parameters:
  S3BucketName:
    Type: String
    Description: Name of existing S3 bucket

Resources:
  MyCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: "A Distribution created with CloudFormation"
        DefaultRootObject: "index.html"
        Enabled: true
        IPV6Enabled: false
        Origins:
          - DomainName: !Sub "${S3BucketName}.s3.amazonaws.com"
            Id: !Sub "${S3BucketName}.s3.amazonaws.com"
            S3OriginConfig:
              OriginAccessIdentity: ""
            OriginAccessControlId: !Ref MyOriginAccessControl
        DefaultCacheBehavior:
          Compress: true
          MinTTL: 3600
          TargetOriginId: !Sub "${S3BucketName}.s3.amazonaws.com"
          ViewerProtocolPolicy: "redirect-to-https"
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: all

  MyOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Description: !Sub "${S3BucketName}.s3.amazonaws.com"
        Name: !Sub "${S3BucketName}.s3.amazonaws.com"
        OriginAccessControlOriginType: "s3"
        SigningBehavior: "always"
        SigningProtocol: "sigv4"
