AWSTemplateFormatVersion: "2010-09-09-OC"
Description: default template generated for organization with master account 062654312577

Organization:
  MasterAccount:
    Type: OC::ORG::MasterAccount
    Properties:
      Alias: ethanle000001-root-user
      RootEmail: ethanle000001@email.com
      AccountName: Ethan
      AccountId: "062654312577"
      Tags:
        budget-alarm-threshold: "10"
        account-owner-email: ethanle000001+master@gmail.com

  OrganizationRoot:
    Type: OC::ORG::OrganizationRoot
    Properties:
      DefaultOrganizationAccessRoleName: OrganizationAccountAccessRole

  DevelopmentAccount:
    Type: OC::ORG::Account
    Properties:
      RootEmail: ethanle000001+development@gmail.com
      AccountName: Development Account
      Tags:
        budget-alarm-threshold: "10"
        account-owner-email: ethanle000001+master@gmail.com

  TestingAccount:
    Type: OC::ORG::Account
    Properties:
      RootEmail: ethanle000001+testing@gmail.com
      AccountName: Testing Account
      Tags:
        budget-alarm-threshold: "10"
        account-owner-email: ethanle000001+master@gmail.com

  ProductionAccount:
    Type: OC::ORG::Account
    Properties:
      RootEmail: ethanle000001+production@gmail.com
      AccountName: Production Account
      Tags:
        budget-alarm-threshold: "10"
        account-owner-email: ethanle000001+master@gmail.com

  DevelopmentOU:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: development
      Accounts:
        - !Ref DevelopmentAccount

  TestingOU:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: testing
      Accounts:
        - !Ref TestingAccount

  ProductionOU:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: production
      Accounts:
        - !Ref ProductionAccount
