AWSTemplateFormatVersion: '2010-09-09-OC'
Description: default template generated for organization with master account 062654312577

Organization:
  ManagementAccount:
    Type: OC::ORG::MasterAccount
    Properties:
      AccountName: Ethan
      AccountId: '062654312577'
      RootEmail: ethanle000001@gmail.com

  OrganizationRoot:
    Type: OC::ORG::OrganizationRoot
    Properties:
      DefaultOrganizationAccessRoleName: OrganizationAccountAccessRole


